---
title: "Monitoramento Sun Coral PACS"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(reshape2)
library(leaflet)
library(ggplot2)
library(vegan)
library(plotly)
library(lubridate)
library(dplyr)
library(sf)
library(crosstalk)
library(htmltools)
library(shiny)

library(RColorBrewer)
palette(brewer.pal(8, "Set2"))
```
```{r dataread, include=FALSE}

dafor_data <- st_read("c//../shp/dafor.shp")
geo_data <- st_read("c//../shp/geomorfologia.shp")

summary(c(dafor_data, geo_data))


```

Map
======================================================================



Column {.sidebar}
-------------------------------------
```{r, echo=FALSE}

dateRangeInput("data", "Data: ", 
          format = "yyyy-mm-dd",
          start = "2022-06-15",
          end =  "2023-12-31",
          separator = " até ",
          )


#https://pkgs.rstudio.com/flexdashboard/articles/shiny.html#inputs-outputs

#https://pkgs.rstudio.com/flexdashboard/articles/shiny.html
#https://rstudio.github.io/leaflet/shiny.html
```


### REBIO Arvoredo e Entorno 2023
Column
-----------------------------------------------------------------------

```{r map}
#https://epsg.io/

#epsg4326 <- leafletCRS(
 #crsClass = "L.Proj.CRS",
  #code = "EPSG:4326",
  #proj4def = "+proj=longlat +datum=WGS84 +no_defs +type=crs",
  #resolutions = 2^(16:7))

# fix map epsg





##https://rstudio.github.io/leaflet/showhide.html

### feijao com arroz
renderLeaflet({

leaflet() %>%
  addTiles() %>%
  #fitBounds(~min(long), ~min(lat), ~max(long), ~max(lat)) %>%   
  addPolylines(data = dafor_data,
               popup = ~paste0("<strong>Localidade:</strong> ", localidade, "<br>",
                              "<strong>Data:</strong> ", data, "<br>",
                              "<strong>N. Mergulhadores:</strong> ", n_divers, "<br>", 
                              "<strong>N. Transectos presente:</strong> " , n_tr_pr),
               labelOptions = labelOptions(noHide = F, direction = "rigth")) %>%  # insert distance
  
  
  addPolylines(data = geo_data,
               popup = ~paste0("<strong>Localidade:</strong> ", localidade, "<br>",
                              "<strong>Data:</strong> ", data, "<br>",
                              "<strong>IAH:</strong> ", iah_seg, "<br>"),
               labelOptions = labelOptions(noHide = F, direction = "right")) %>% # insert distance
  
  addMiniMap(toggleDisplay = T)
})


#https://rstudio.github.io/leaflet/shapes.html




```

